### ISSUE TITLE
Introduce sharding capabilites

### ISSUE THREAD

**Issue by PumpkinSeed** [PumpkinSeed/bucket#75]
Investigate about sharding, how should we put into the framework on a simple way.
https://developer.couchbase.com/documentation/server/3.x/developer/dev-guide-3.0/sharding.html

**Comment by tetff** [comment]
https://docs.couchbase.com/server/6.0/learn/buckets-memory-and-storage/vbuckets.html
According to this, sharding via vBuckets happens automatically in couchbase.
